//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Carto
    {
        [Display(Name = "Número do Cartão")]
        [Required(ErrorMessage = "Informe o número do cartão", AllowEmptyStrings = false)]
        public decimal NrCartao { get; set; }

        [Display(Name ="Número do Lote")]
        public Nullable<int> NrLote { get; set; }
    }
}
